# Limit request zone
limit_req_zone $binary_remote_addr zone=one:10m rate=6r/m;

# App 1
server {
	listen 3000 default_server;
	listen [::]:3000 default_server;


	root /var/www/html;

	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		proxy_pass http://localhost:8000;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection 'upgrade';
		proxy_set_header Host $host;
		proxy_cache_bypass $http_upgrade;
	
		limit_req zone=one burst=1 nodelay;	
	}
}

# App2
server {
        listen 3001 default_server;
        listen [::]:3001 default_server;

        server_name _;

        location / {
                proxy_pass http://localhost:8001;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;

                limit_req zone=one burst=1 nodelay;
        }
}
